

INSERT INTO pregunta  (enunciado, respuestaa, respuestab, respuestac, solucion, categoria, dificultad)
VALUES
('¿Qué es el ORM en el contexto del acceso a datos?', 'A) Object-Relational Mapping', 'B) Object-Resource Mapping', 'C) Object-Role Modeling', 'a', 1, 1),
('¿Cuál de las siguientes no es una técnica para acceder a datos en una aplicación multiplataforma?', 'A) JDBC', 'B) ODBC', 'C) SQL Server', 'c', 1, 1),
('¿Cuál es el objetivo principal de un sistema de gestión de bases de datos (SGBD)?', 'A) Almacenar y administrar los datos de una aplicación', 'B) Desarrollar interfaces de usuario atractivas', 'C) Optimizar el rendimiento del código fuente', 'a', 1, 1),
('¿Cuál es el lenguaje de consulta utilizado para acceder a una base de datos relacional?', 'A) SQL', 'B) HTML', 'C) XML', 'a', 1, 1),
('¿Qué significa el término "transacción" en el contexto del acceso a datos?', 'A) Una unidad de trabajo lógica que debe ser ejecutada en su totalidad o no ejecutarse en absoluto', 'B) El proceso de acceder a datos de forma simultánea desde múltiples ubicaciones', 'C) La manipulación de datos a nivel de bits en una estructura de almacenamiento', 'a', 1, 1),
('¿Cuál de las siguientes no es una ventaja del acceso a datos mediante API REST?', 'A) Flexibilidad en el intercambio de datos entre diferentes plataformas', 'B) Mayor seguridad en la transferencia de datos', 'C) Escalabilidad y facilidad de integración', 'b', 1, 1),
('¿Qué es la normalización de datos en el contexto del acceso a datos?', 'A) El proceso de organizar los datos en una estructura lógica y eficiente', 'B) El proceso de realizar copias de seguridad de los datos', 'C) El proceso de encriptar los datos para mayor seguridad', 'a', 1, 1),
('¿Qué es un controlador de base de datos en el contexto del acceso a datos?', 'A) Un componente software que permite la comunicación entre una aplicación y una base de datos', 'B) Una regla de seguridad que limita el acceso a los datos sensibles', 'C) Una técnica de encriptación utilizada para proteger los datos almacenados', 'a', 1, 1),
('¿Qué es la concurrencia en el contexto del acceso a datos?', 'A) La capacidad de acceder y manipular datos al mismo tiempo desde múltiples hilos o procesos', 'B) La capacidad de recuperar datos de forma eficiente utilizando índices', 'C) La capacidad de realizar operaciones de agregación en grandes conjuntos de datos', 'a', 1, 1),
('¿Cuál de las siguientes no es una técnica para mejorar el rendimiento en el acceso a datos?', 'A) Caché de datos', 'B) Compresión de datos', 'C) Fragmentación de datos', 'c', 1, 1),
('¿Cuál es el propósito de una consulta SQL SELECT en el acceso a datos de una aplicación multiplataforma?', 'A) Recuperar datos específicos de una base de datos', 'B) Insertar nuevos registros en una tabla', 'C) Actualizar registros existentes en una tabla', 'a', 1, 1),
('¿Cuál es el objetivo principal de la optimización de consultas en el acceso a datos?', 'A) Mejorar el rendimiento y la eficiencia de las consultas', 'B) Garantizar la integridad de los datos almacenados', 'C) Realizar copias de seguridad regulares de la base de datos', 'a', 1, 1),
('¿Qué es el mapeo objeto-relacional (ORM) en el acceso a datos?', 'A) Una técnica para convertir objetos en estructuras de datos relacionales', 'B) Una técnica para realizar copias de seguridad de los datos', 'C) Una técnica para realizar consultas complejas en una base de datos', 'a', 1, 1),
('¿Cuál es el propósito de un índice en el acceso a datos de una aplicación?', 'A) Mejorar el rendimiento de las consultas y búsquedas de datos', 'B) Establecer reglas de seguridad para el acceso a los datos', 'C) Realizar análisis estadísticos sobre los datos almacenados', 'a', 1, 1),
('¿Cuál de las siguientes NO es una forma de acceso a datos en una aplicación multiplataforma?', 'A) Acceso directo a los archivos de la base de datos', 'B) Acceso mediante servicios web', 'C) Acceso a través de consultas SQL', 'a', 1, 1),
('¿Cuál es el propósito de las transacciones en el acceso a datos?', 'A) Mantener la consistencia y la integridad de los datos', 'B) Mejorar el rendimiento de las consultas', 'C) Optimizar la capacidad de almacenamiento de la base de datos', 'a', 1, 1),
('¿Qué es la fragmentación de datos en el contexto del acceso a datos?', 'A) Dividir una tabla grande en fragmentos más pequeños para distribuirlos en diferentes ubicaciones', 'B) Encriptar los datos para proteger su confidencialidad', 'C) Realizar copias de seguridad periódicas de la base de datos', 'a', 1, 1),
('¿Cuál de las siguientes NO es una técnica de seguridad utilizada en el acceso a datos?', 'A) Encriptación de datos', 'B) Autenticación de usuarios', 'C) Compresión de datos', 'c', 1, 1),
('¿Qué es la normalización de base de datos en el acceso a datos?', 'A) Un proceso para organizar y estructurar los datos en tablas relacionales', 'B) Una técnica para optimizar el rendimiento de las consultas', 'C) Una técnica para realizar copias de seguridad de la base de datos', 'a', 1, 1),
('¿Cuál es el propósito de la gestión de la caché en el acceso a datos?', 'A) Mejorar el rendimiento al almacenar en memoria los datos más utilizados', 'B) Realizar copias de seguridad automáticas de la base de datos', 'C) Establecer reglas de seguridad para el acceso a los datos', 'a', 1, 1);